### ISSUE TITLE
Convert metagenomic tutorial into a ipynb (python notebook)

### ISSUE THREAD

**Issue by ubhuiyan** [GW-HIVE/PredictMod#106]

**Comment by ubhuiyan** [comment]
Received feedback from our intern Khushi that a Python notebook might make the tutorial easier to follow. I am transferring all information to the notebook, and adding some more parts. This will be uploaded to the PredictMod repository once completed.

**Comment by lorikrammer** [comment]
@ubhuiyan I can't seem to find the metagenomic tutorial in github. Can you provide a link or the folder you saved it in? Thanks.

**Comment by ubhuiyan** [comment]
@lorikrammer here is the link: [https://github.com/GW-HIVE/PredictMod/blob/dev/MG_python/metagenomic_ML_tutorial.ipynb](url)
