### ISSUE TITLE
Deep Dive & Demo Preparation

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#108]
**INITIAL REQUEST FROM COR**
I have been reviewing the contract deliverable list/schedule, those recurring/nonrecurring in the monthly reports as well as some initial deliverables (such as the configuration plan), and I’m seeking a deep dive to summarize the last six months of efforts, expected next six months (through the current period of performance of 12/11/2023), milestones hit, expected milestones through the POP end, as well as an inventory of deliverables completed vs not, to include the configuration plan (which I cannot find). Also, as an FYI – the github links from earlier this year seem to be broken.

How long will you/your team need to prepare for this presentation? I would like to have this scheduled by 07/21/2023, if possible. Please share with the GWU team and let me know.

**GW RESPONSE**
Our team is available for a virtual demo and presentation on 7/21/2023, preferably before 11:00 AM EDT. Is there a time you prefer to meet?

As for the CM Plan, there was some misunderstanding on our end based on the wording in the contract, and I apologize for not getting that to you earlier. We do have all of the materials, I will compile the plan and get it to you as soon as possible. 

The broken links are likely a result of the security settings on GitHub, I’ll look into this and get back to you with functional links.

**VA RESPONSE**
Thanks, Lori – I appreciate it – let’s schedule for 9am 7/21/2023. Regarding the CM Plan and deliverables, no particular rush – ideally by Monday the 17th of July so that our team has time to review your progress ahead of the demo. Thanks again for taking the time to loop us all in at the same time – with the movement of PM’s, new/returning folks to our team, this will be very helpful to ensure that we are tracking your team’s progress and helping to alleviate barriers as best we can.

Please let me know if you need any support in the meantime.

**Comment by lorikrammer** [comment]
Tasks:

- [ ] Lori to update Milestones document #111
- [ ] Create PowerPoint Presentation & Practice Demo
- [ ] Schedule a run through with Raja in advance of 7/21/2023
- [ ] CM Plan: review with Urnisha & Pat. #110
- [ ] Descriptive Text: #109

**Comment by ubhuiyan** [comment]
Link to bare slides: [VA Presentation Slides](https://docs.google.com/presentation/d/1HGfX8Ke2klsukvQCnj4pjwbEogyMz4xKDCnGUEp6QRo/edit#slide=id.g257c880a096_0_89)
