### ISSUE TITLE
v0.3.1 Deployment

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#120]
Hi Pat, 

Raja has approved the mockups discussed in our meeting yesterday. Please use [this link](https://www.figma.com/file/wxHNsOw4J2LKdmhFOjGIPL/v0.3.0?type=design&node-id=0%3A1&mode=design&t=HLca4EX4EHIMylxG-1) to view the mockups, and let me know if you have any questions. He had some additional comments which I will add to the mockups and you can incorporate them, time permitting.

**I would like to set a deadline of 8/24 for deployment, allowing some time for delays/blockers. Is this feasible?**

**Comment by lorikrammer** [comment]
@pmcneely I have implemented the changes Raja requested when I met with him today. You can find the updated v0.3.1 file [here](https://www.figma.com/file/REjECWA9RlEHFtajBwjruY/v0.3.1?type=design&node-id=0%3A1&mode=design&t=YkJful2hyfxdQohO-1). If we can make this improvements with the August release that would be ideal, but if necessary, v0.3.0 will be sufficient. Please let me know if you have any questions!

**Comment by pmcneely** [comment]
> I would like to set a deadline of 8/24 for deployment, allowing some time for delays/blockers. Is this feasible?

8/24 might be possible, but if there are major bugs/blockers (and there could be, I'll be triaging tomorrow and Monday) then 8/28 is more likely.

**Comment by pmcneely** [comment]
Great, thanks for the links! I'll propose something like this ["Design Changelog"](https://github.com/GW-HIVE/PredictMod/blob/main/Frontend%20Design%20Changelog.md). Obviously, we can change the location and format but it's a central resource we can easily share :)
