### ISSUE TITLE
VA Acceptance Signoff

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#124]
**Primary: Lori | Backup: Urnisha**
Finish PredictMod Signoff slides and fill out the Signoff Template found in [this folder](https://gwu0.sharepoint.com/sites/PredictMod-GRP/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FPredictMod%2DGRP%2FShared%20Documents%2F05%5FProduct%20Management%2F06%5FSignoff&viewid=9bd8e9cf%2Dba0f%2D413e%2Db13a%2Da5b506639bfc). Work with COR, CO & Raja to obtain VA signoff of PredictMod application.

**Comment by lorikrammer** [comment]
Hi @ubhuiyan, when you get a moment, can you take a look at the signoff presentation, which details the signoff activities laid out in the contract and our accomplishments so far? I'd like to discuss this with you today or Monday if possible. If you don't get a chance before we meet in-person, no worries.

**Comment by ubhuiyan** [comment]
@lorikrammer I will take a look at them!

**Comment by lorikrammer** [comment]
The Signoff document was sent to the VA on 9/6 and signed by Josh and Nicole. We are waiting on Michael Haydo's signature before Raja signs. A copy of the document will be included in the Sept monthly report.
