### ISSUE TITLE
Collaborator Tasks: Jorge Sepulveda

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#133]
**Primary: Urnisha | Backup: Lori**

- [x] Attend Design Thinking Session on 9/12/2023
- [x] Assist with PredictMod EHR model training

**Comment by ubhuiyan** [comment]
Dr. Sepulveda will request for the pickled (stored) model to be exported. Upon this approval, we will upload the package to GitHub to to integrate with PredictMod. He and I will reconvene on 10/10/23 after we are both back from our respective vacations.
