### ISSUE TITLE
Update GitHub Readme

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#137]
Hi @pmcneely when you get a chance, please update the GitHub readme with the folders you verbally described in the planning session. If possible, I'd also love a written blurb (a comment here is fine) describing how the backend is configured (you also explained this briefly in the planning session, how the backend is 'wires'). Let me know if you have questions. Thanks!

**Comment by pmcneely** [comment]
There's a fair amount of the code (and material) in the Readme that will be deprecated by the time I've completed the interface refactor.

I'll review later in the month once the refactor & deployment is complete.
