### ISSUE TITLE
EHR python prediction resources

### ISSUE THREAD

**Issue by pmcneely** [GW-HIVE/PredictMod#141]
@ubhuiyan Could you please move any EHR/python related resources to an appropriate EHR location (rather than the `Metagenomic_predict` location)? I can move the `EHR_ptyhon.py` script but it's not clear to me if that's the only resource currently.

**Comment by ubhuiyan** [comment]
Hi @pmcneely. I have created a separate folder called "EHR_python" that should contain all the python code meant for EHR data.

**Comment by pmcneely** [comment]
Perfect, thank you. I'll close this up then.
