### ISSUE TITLE
Work with Dr. Sen to Obtain CAG Access

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#143]
Our COR Josh recommended that Abel connect with Dr. Sen’s team and whomever established his PIV and access to have it reinstated and grant him remote access through the Citrix Access Gateway (CAG) portal. If this is not possible, please let me know – his supervisor in the VA system is currently listed as Dr. Sen, so I would advise him to start there.

@AbelArgaw can you reach out to Dr. Sen to get this process started?

**Comment by AbelArgaw** [comment]
Yes, I will reach out to Dr Sen

**Comment by lorikrammer** [comment]
@AbelArgaw Closing out this ticket as you now have CAG access.
