### ISSUE TITLE
Julia: Do you have recommand for Markdown Editor?

### ISSUE THREAD

**Issue by Mute-yc** [GW-HIVE/PredictMod#15]
I used to use Typora but the latest version of it is fee-based. I really like the real live preview function they provided. Do you use Visual Studio Code to write a README file? I wish to find a simple but powerful editor like Typora. 
This issue is only posted for testing.

**Comment by HadleyKing** [comment]
@Mute-yc 
Good Question!
I usually edit md files in a plain text editor I use for Mac called [TextMate](https://macromates.com/). This is MacOS specific and really any editor you like is fine. 

But to view it I use the [Chrome Markdown Viewer](https://chrome.google.com/webstore/detail/markdown-viewer/ckkdlimhmcjmikdlpkmbgfkaikojcbjk). Then you just open your local md file using Google Chrome and it is rendered exactly how it would be on the web.

**Comment by rajamazumder** [comment]
Our lab recommends TextPad as text editor. It is free to download.

-- 
Raja Mazumder, Ph.D.
Professor
Department of Biochemistry and Molecular Medicine
School of Medicine & Health Sciences
The George Washington University
Ross Hall, Room 540
2300 Eye Street N.W.
Washington, DC 20037
Phone office: 202-994-5004
Phone lab: 202-994-3639
Phone dept: 202-994-5311
Fax: 202-994-8974
