### ISSUE TITLE
FHIR Demo & Collab with Titus Schleyer

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#289]
Hi Pat, when you are back, as per Raja's recommendation, can you reach out to Titus Schleyer to show how we plan to use FHIR? Thanks!

**Comment by lorikrammer** [comment]
@pmcneely I think you mentioned you've been in contact with Titus. Can you update/close out this ticket as needed? Thanks!

**Comment by pmcneely** [comment]
So far I haven't come across any blockers, so I haven't spoken with Titus or any other folks regarding FHIR implementation. We can table this for now.
