### ISSUE TITLE
ML/AI MATLAB-type Packaging Tool

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#291]
Incorporation of MATLAB-like click-and-play ML/AI package tool for the PredictMod interface.

**Comment by pmcneely** [comment]
@lorikrammer This task is really the tutorial that Miguel is putting together, correct?

**Comment by lorikrammer** [comment]
I originally created the ticket based on our discussion at the scientific retreat. But I think Miguel's tool is sufficient for now. I'll close out this ticket.
