### ISSUE TITLE
Help Page Table of Contents Links

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#304]
The 'Table of Contents' links don't match the updated content in the _help_ page.

the links at the top need to be in html or javascript, if the columnar format is to be kept. That means a second file to be updated whenever anchors are changed in the markdown. You are welcome to match the javascript anchors with the markdown links, or I can review and handle it Friday. The ToC block of links is in [this file](https://github.com/GW-HIVE/PredictMod/blob/main/vuetify_app/src/views/Help.vue) in the router-link sections
[Help.vue](https://github.com/GW-HIVE/PredictMod/blob/main/vuetify_app/src/views/Help.vue)
[template](https://app.slack.com/client/TFEH1PSKB/template)

**Comment by Reeya123** [comment]
I noticed that some of the links in the Table of Contents, like 'Step 1: Selecting a Condition' under the Query Builder section, don’t have corresponding sections on the page to link to. So could be that the information sections might be incomplete, as certain ToC items don’t have matching content.

Could you confirm if the content for these missing sections needs to be added? Or should we remove these links from the ToC until the corresponding sections are available? Let me know how you'd like to proceed with aligning the ToC links to actual content sections on the page

**Comment by lorikrammer** [comment]
The TOC is outdated; please match the links to the new headers. Thanks!
