### ISSUE TITLE
Paragraph Spacing

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#306]
No spacing between paragraphs on the following pages: tutorial, new models, model-specific content.
PredictMod: https://hivelab.biochemistry.gwu.edu/predictmod/
Code: https://github.com/GW-HIVE/PredictMod/blob/main/vuetify_app/src/docs/help_content/help.md

**Comment by pmcneely** [comment]
Closing since it has been merged.
