### ISSUE TITLE
PredictMod v1.0 Push to Production

### ISSUE THREAD

**Issue by HadleyKing** [GW-HIVE/PredictMod#44]
Make available the PredictMod interface through here
https://hive.biochemistry.gwu.edu/gfkb/predictmod

To do this I think @rykahsay will have to enable that URL and the subsequent child pages for it on the HIVE server. We will be using a Vue (JavaScript) UI that will communicate with a Django API (Python). I plan on deploying them from the `/data/software` directory. 
I do not think it will be much work, but if it will be (or you have a different preference for deployment) let me know.

**Comment by lorikrammer** [comment]
Hi @rykahsay, following up on this. It looks like we have slightly different workflow for website production, and we will need 

- The machine running [hive.biochemistry.gwu.edu/gfkb/predictmod](http://hive.biochemistry.gwu.edu/gfkb/predictmod) should be provisioned with Docker, and appropriate permissions for running the containers.
- We'll then build a docker container with the above MatLab, NVM, and Python built-in.

Can you tell me how we would obtain a license to run MATLAB in Docker?

**Comment by rykahsay** [comment]
@lorikrammer 
Since we are transitioning to the new app for our lab pages, I am waiting for @kee007ney to set up the new domain so that I can build the new APP.

**Comment by lorikrammer** [comment]
Sounds good. @kee007ney is there anything you need from the PredictMod team to set up the new domain? Is it feasible to setup the new domain by the end of this week?

**Comment by pmcneely** [comment]
@rykahsay Are you able to walk me (or Jonathon and myself) through your process of standing up the new app? I'd like to make sure that we deploy consist with the "new" (dockerized) method. If you can point me to code that will work perfectly as well.

**Comment by lorikrammer** [comment]
@pmcneely Based on your announcement this morning, it sounds like this is done! I understand there are some bugs/hiccups. If you prefer to use this thread to address those, I can re-open this ticket. Thanks!
