### ISSUE TITLE
Data Dictionary v1.0

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#59]
Refine and release [Data Dictionary v1.0](https://gwu0.sharepoint.com/:x:/r/sites/PredictMod-GRP/Shared%20Documents/PredictMod%20Data%20Dictionary%20Versions/Data%20Dictionary%20v1.0.xlsx?d=wc86a6611a1b540279d84194f4db6fc29&csf=1&web=1&e=g0ekYm).
This will be done in conjunction with [Data Mapping v1.0](https://gwu0.sharepoint.com/:x:/r/sites/PredictMod_VA/_layouts/15/Doc.aspx?sourcedoc=%7B1F8B391A-11E7-4BBE-AFB6-E2C7C72F68C4%7D&file=EHR%20Variables.xlsx&action=default&mobileredirect=true).

**Comment by lorikrammer** [comment]
Use this link to reference the ARGOS data dictionary: 
https://github.com/FDA-ARGOS/data.argosdb/tree/main/data_dictionary/v1.1

**Comment by lorikrammer** [comment]
Use [this link](https://gwu0.sharepoint.com/:x:/r/sites/PredictMod_VA/Shared%20Documents/EHR%20Variables.xlsx?d=w1f8b391a11e74bbeafb6e2c7c72f68c4&csf=1&web=1&e=jArqq0) to access the EHR Variables List. I've reached out to Arad to confirm these are the data they plan to collect and to provide additional baseline demographic variables. I'll update this list as needed. Thanks!

**Comment by lorikrammer** [comment]
**Response from Arad**
I have also gone through the sharepoint doc, and answered most of the listed items. The ones left blank are currently a no, but can be added if Dr. Sen is agreeable. Items 63-90 are potential yes based on our lab staff ability to perform serum ELISA and quantity of blood that we collect. Dr. Nandula will prioritize those according to what we see with the rest of the data, and those values will become available much later than the assessments conducted in the clinic or run as part of Standard of Care in the VA Lab.

**Comment by lorikrammer** [comment]
[Data Dictionary v1.0](https://gwu0.sharepoint.com/:x:/r/sites/PredictMod-GRP/Shared%20Documents/PredictMod%20Data%20Dictionary%20Versions/Data%20Dictionary%20v1.0.xlsx?d=wc86a6611a1b540279d84194f4db6fc29&csf=1&web=1&e=g0ekYm)

**Comment by lorikrammer** [comment]
Hi @steph-sing, 

When you have some time, can you take a look at [Data Dictionary v1.0](https://gwu0.sharepoint.com/:x:/r/sites/PredictMod-GRP/Shared%20Documents/PredictMod%20Data%20Dictionary%20Versions/Data%20Dictionary%20v1.0.xlsx?d=wc86a6611a1b540279d84194f4db6fc29&csf=1&web=1&e=gfnnEy)? There are still some [unconfirmed variables](https://gwu0.sharepoint.com/:x:/r/sites/PredictMod-GRP/Shared%20Documents/Project%20Documents/Unconfirmed%20Variables.xlsx?d=w8d2c2894c8ca4f4cb6fc1bbad62bdf17&csf=1&web=1&e=tGchaN) I'm not sure about, but I think this is a good place to start. Please reference [Data Mapping v1.0](https://gwu0.sharepoint.com/:x:/r/sites/PredictMod-GRP/Shared%20Documents/PredictMod%20Data%20Dictionary%20Versions/Data%20Mapping%20v1.0.xlsx?d=w967d6da9593848ebb7d812d21c4eda5b&csf=1&web=1&e=x4UBHO) as well. For both documents, I included some planned additions for the v1.1 release.

Once we have v1.0 finalized, I can coordinate with Dr. Sepulveda and Arad about the EPIC and MDClone data sources.

Thanks!

**Comment by steph-sing** [comment]
@lorikrammer We may need to set up a meeting today to go over all the edits for the data dictionary, and then notes can be logged in this ticket. Please let me know your availability. 

__

**Comment by steph-sing** [comment]
version v1.1 draft edits: 

https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/
- add project title, project description, describe each tab and that files purpose, more clearly define column header definitions, add info about file size, how many column or rows, and version
- for the 'data_range' column in the obs_list : use set standard lab intervals to create the data ranges: https://www.labcorp.com/resource/critical-values
- for 'data_metric' column in obs_list: change to 'data_unit' or 'unit'; also pull from the document above
- when you get to the data_types part, @steph-sing will fill them in for you, plus a new patterns column 
-
