### ISSUE TITLE
Develop User Stories for PredictMod UI development targets

### ISSUE THREAD

**Issue by pmcneely** [GW-HIVE/PredictMod#65]
Develop basic user stories to guide downstream development of the UI. Examples include:
- When first arriving at the site, should it immediately ask for a file upload, or give information about the tool and options to use it?
- After submitting a job, should the (1) website stay static, (2) show some sort of status, or (3) provide output via email, file download, etc?
I'm sure other stories will develop as we move forward. 
@lorikrammer @Mute-yc @pmcneely

**Comment by lorikrammer** [comment]
This is how I envision the experience a researcher will having using PredictMod. I'm not sure if the format is appropriate for user stories, but we can discuss in the meeting later this week.

1. I go to [hive.biochemistry.gwu.edu/gfkb/predictmod].
2. The page is static/readable (no popups), and I can read about PredictMod, disclaimers, and instructions.
4. I (scroll if needed) and select the "Upload File" button. _Maybe there's a button at the top I can press to take me to the upload file button if the content is too long?_
6. I am prompted to confirm the file type ("PredictMod input must be in the following formats, etc." blurb). _This might be too complicated for v1.0, maybe something to incorporate in later versions and have a written notice below the "Upload File" button?_
7. I select "I understand" to confirm. _Dependent on step 6_
8. I upload my file.
9. I select "run"
10. I receive a notice that my submission has been received, and a loading icon/message appears. _I would think a loading bar/circle would be the easiest to implement, but maybe a refresh message or an email would be better? This can be improved in v2.0_
11. I receive my result _Future versions may have resources or additional figures for me to review_

**Comment by lorikrammer** [comment]
![Image](https://user-images.githubusercontent.com/106612903/214395369-1594fd34-f6df-463f-a047-856a3aed2e96.png)

**Comment by pmcneely** [comment]
Looks like a great place to start development. We can catch up more Thursday/or earlier as you and @Mute-yc feel is appropriate.
