### ISSUE TITLE
Explore VA Interface

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#72]
Figure out how the VA interface works on a very close level. Think about what questions to ask Dr. Sen about it.

**Comment by ubhuiyan** [comment]
Blocker: VA Vista does not appear to be publicly available. Planning on asking the synthetic data generation team at VA how this database can be accessed.

**Comment by lorikrammer** [comment]
At the end of the year we should be able to give a presentation on Vista so if you could work with Dr. Sen to understand how VA clinicians use Vista to access patient data, that would be fantastic.

I have some questions about it from Raja: What system to they use (ie Vista)? What type of data can he access? What data can be entered/input? Can he download anything from this interface? etc.

**Comment by ubhuiyan** [comment]
I am in correspondence with Dr. Sen to get preliminary information that I can use to help me access this resource. I have unsuccessfully been able to access this resource in previous attempts, so I have asked Dr. Sen for some guidance and whether this is the platform he intends to upload his patients' records from the keto and weight loss drug studies into.

**Comment by ubhuiyan** [comment]
The VA VISTA is actually named VISTAWeb. It is a platform designed for VA clinicians to provide necessary information pertaining to their patients. There are several VISTA-like login pages; however, none of them had a URL ending in .gov. I found a pdf document discussing VISA's use-case and it appears the website may have been redacted.  

Link to document:[ ](https://www.va.gov/vdl/documents/Clinical/VistaWeb/vistawebusermanual.pdf)

**Comment by lorikrammer** [comment]
Hey @ubhuiyan how is research on CPRS going?

**Comment by ubhuiyan** [comment]
@lorikrammer It is going well. I will document what I have found within the Justification Document v2.0 if that works.
