### ISSUE TITLE
Link PredictMod domains available at `hivelab.biochemistry.gwu.edu` through reverse proxies

### ISSUE THREAD

**Issue by pmcneely** [GW-HIVE/PredictMod#76]
We'd like PredictMod landing pages at `hivelab.biochemistry.gwu.edu/gfkb/predictmod{-beta}`. 

I will provide docker containers which expect reverse proxy service at port 4242 (`predictmod`) and port 4243 (`predictmod-beta`).

**Comment by pmcneely** [comment]
@rykahsay @lorikrammer 
Please configure the server VMs for reverse proxy of websites at ports 4242 and 4243.

**Comment by lorikrammer** [comment]
@pmcneely As I understand it, this has been done as well, correct? Do we have a beta site set up?

**Comment by pmcneely** [comment]
@lorikrammer Yes this is complete. There is a landing page at `hivelab.tst.biochemistry.gwu.edu/gfkb/predictmod`. There are 4 possible sites total, under combinations of `{tst/no-tst}` in the address subdomain and predictmod{,-beta} in the landing page. Since we only have the one page for now, I've not hooked up any additional targets.
