### ISSUE TITLE
Burn Pit Analysis Addendum Request

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#80]
Submit an addendum request to the VA for dry-lab Burn Pit Analysis model development. Contingent on PAH table #78.

- [ ] Prepare a draft to be reviewed by Steph & Raja
- [ ] Submit draft to Dr. Sen for approval
- [ ] Submit final request to the VA.

**Comment by lorikrammer** [comment]
Reference the [Burn Pit Analysis](https://docs.google.com/document/d/1RU05cMtfqgeokLolJ3az_CYSSoEktaBTpl24tqjYf20/edit#) draft.

**Comment by lorikrammer** [comment]
@steph-sing can you take a look at the [Burn Pit White Paper](https://docs.google.com/document/d/1RU05cMtfqgeokLolJ3az_CYSSoEktaBTpl24tqjYf20/edit?usp=sharing) draft and provide feedback? We will also send it to Raja and Dr. Sen for approval prior to sending it to the VA. Thanks!!

**Comment by steph-sing** [comment]
Received. Can you please include a timeline of when you need the review completed by me?

**Comment by lorikrammer** [comment]
I spoke with Raja today and we can hold off on the review until we do a more complete search for the RNAseq data. I'll be in touch when it's ready for review, and I can give you an appropriate window of time to do so (3 days or longer).
