### ISSUE TITLE
Data Dictionary v1.1

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#91]
Data Dictionary v1.1 release will include additional variables, data types, ranges, and metrics.

**Comment by lorikrammer** [comment]
version v1.1 draft edits:

https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

- add project title, project description, describe each tab and that files purpose, more clearly define column header definitions, add info about file size, how many column or rows, and version
- for the 'data_range' column in the obs_list : use set standard lab intervals to create the data ranges: https://www.labcorp.com/resource/critical-values
- for 'data_metric' column in obs_list: change to 'data_unit' or 'unit'; also pull from the document above
- when you get to the data_types part, @steph-sing will fill them in for you, plus a new patterns column

**Comment by lorikrammer** [comment]
Hi @steph-sing, can you help with the Data Dictionary & Mapping docs? Khushi added the data types, ranges, and units for a subset of variables, but we will need to add them for the rest of the properties. The readme and release notes should be updated as well, I didn't get a chance to implement the changes discussed in our last visit:
- add project title, project description, describe each tab and that files purpose, more clearly define column header definitions, add info about file size, how many column or rows, and version

I am happy to hop on a call and clarify any of this as well! Please let me know if this is something you think you can complete by 08/31/2023. If not, I can dedicate some additional time to help out. 

Thanks!

**Comment by steph-sing** [comment]
Next steps as discussed with Lori on 8/31:

@lorikrammer can you update the sharepoint to reflect the following files:
v1.0_data_dictionary_final (make sure release notes are up to date)
v1.1_data_dictionary_final (make sure release notes include the changeLog from v1.0-1.1)

@steph-sing  will copy v1.1 final, work on it offline, and release back to sharepoint like this:
v1.2_data_dictionary_draft 
(we can approve and make minor edits in sharepoint, once approved draft will be replaced as final)
All finals should be Read Only

**Comment by lorikrammer** [comment]
@steph-sing I've updated the folder based on our discussion today. Please take a look and let me know if you have any questions. the draft version 1.2 should be ready for your edits. Thanks!
