### ISSUE TITLE
PredictMod v1.0 Testing

### ISSUE THREAD

**Issue by lorikrammer** [GW-HIVE/PredictMod#97]
Test PredictMod v1.0 to ensure it meets minimum viable product qualifications.

**Comment by ubhuiyan** [comment]
A single patient EHR Excel file was uploaded into the PredictMod interface. Once the upload was successful, the file was submitted for prediction. The prediction for the first unknown patient response came out as responder and the second patient as non-responder. The metagenomic section of PredictMod currently uses the EHR neural nets for predictions; however, Pat and I will figure out how to fix this to ensure MG data is only allowed in the MG submission field.
